"""
Q187: Find the Difference (XOR)
==================================
Problem: String t is generated by random shuffling string s and adding
one more letter. Find the added letter.

Example:
    s="abcd", t="abcde" -> 'e'
    s="",     t="y"     -> 'y'
"""

def find_the_difference(s, t):
    result = 0
    for ch in s + t:
        result ^= ord(ch)
    return chr(result)

def find_the_difference_v2(s, t):
    from collections import Counter
    diff = Counter(t) - Counter(s)
    return list(diff.keys())[0]

if __name__ == "__main__":
    print(find_the_difference("abcd", "abcde"))  # 'e'
    print(find_the_difference("", "y"))           # 'y'
    print(find_the_difference_v2("a", "aa"))      # 'a'
